<?php
$title = 'Add new team';
$this->headTitle($title.' - ');
?>
<script>
        tinyMCE.init({
            mode : "textareas",
            theme : "advanced",
                        //elements : "textareaId",
            plugins : "advimage,advlink,media,contextmenu,table",
            theme_advanced_buttons1_add_before : "newdocument,separator",
            theme_advanced_buttons1_add : "fontselect,fontsizeselect",
            theme_advanced_buttons2_add : "separator,forecolor,backcolor,liststyle",
            theme_advanced_buttons2_add_before: "cut,copy,separator,",
            theme_advanced_buttons3_add_before : "",
            theme_advanced_buttons3_add : "media,tablecontrols",
            theme_advanced_toolbar_location : "top",
            theme_advanced_toolbar_align : "left",
            extended_valid_elements : "hr[class|width|size|noshade]",
            paste_use_dialog : false,
            theme_advanced_resizing : true,
            theme_advanced_resize_horizontal : true,
            apply_source_formatting : true,
            force_br_newlines : true,
            force_p_newlines : false,  
            relative_urls : true
        });
</script>

<h1>
	<i class="icon-large icon-tasks"></i>
	<?php echo $this->escapeHtml($title); ?>
</h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('team', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('teamId'));
?>
<div class="row-fluid text-center">
	<div class="span12 text-center">
		<?php
		echo $this->formRow($form->get('name'));
		echo $this->formRow($form->get('overheadCost'));
		?>
		<div class="processTextareaContainer">
			<div style="margin: auto; width: 600px;">
				<?php echo $this->formRow($form->get('itResources')); ?>
			</div>
		</div>
	</div>
</div>
<div class="form-actions text-right">
	<a href="<?php echo $this->url('dashboard') ?>" class="btn pull-left">
		<i class="icon-chevron-left"></i> Back to Dashboard
	</a>

	<?php echo $this->formSubmit($form->get('submit')) ?>
	<a href="<?php echo $this->url('team') ?>" class="btn btn-danger">Cancel</a>
</div>
<?php echo $this->form()->closeTag(); ?>