<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add new user';
$this->headTitle($title.' - ');
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('user', array('action' => 'add')));
$form->prepare();
echo $this->form()->openTag($form);
/*
echo $this->formHidden($form->get('user_id'));

echo $this->formRow($form->get('teamId'));
echo $this->formRow($form->get('username'));
echo $this->formRow($form->get('password'));
echo $this->formRow($form->get('passwordConfirmation'));
echo $this->formRow($form->get('firstName'));
echo $this->formRow($form->get('lastName'));
echo $this->formRow($form->get('address'));

echo $this->formSubmit($form->get('submit'));*/
echo $this->formCollection($form);
echo $this->form()->closeTag();