<?php
$title = 'Delete user';
$this->headTitle($title.' - ');
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($user->username); ?>' named
    '<?php echo $this->escapeHtml($user->firstName).' '.$this->escapeHtml($user->lastName); ?>'?
</p>
<?php
$url = $this->url('user', array(
    'action' => 'delete',
    'id'     => $this->user_id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="user_id" value="<?php echo (int) $user->user_id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>