<?php
if (!$this->enableRegistration) {
    echo "<h3 class=\"text-center text-error\">Registration is disabled</h3>";
    return;
} ?>
<div class="row-fluid">
    <div class="span4">
        <div class="well">
        <?php
            $form = $this->registerForm;
            $form->prepare()
                ->setAttribute('action', $this->url('zfcuser/register'))
                ->setAttribute('method', 'post') ?>

        <?php echo $this->form()->openTag($form) ?>
            <legend>Register</legend>
            <?php foreach ($form as $element): ?>
                <?php if (!$element instanceof Zend\Form\Element\Button): ?>
                    <dt><?php echo $this->formLabel($element) ?></dt>
                <?php endif ?>
                <?php if ($element instanceof Zend\Form\Element\Button): ?>
                    <dd><?php echo $this->formButton($element->setAttribute('class', 'btn btn-sa-orange')) ?></dd>
                <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
                    <dd><?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?></dd>
                <?php else: ?>
                    <dd><?php echo $this->formInput($element->setAttribute('class', 'span12')) .
                        $this->formElementErrors()
                            ->setMessageOpenFormat('<p class="text-error">')
                            ->setMessageCloseString('</p>')
                            ->render($element) ?>
                    </dd>
                <?php endif ?>
            <?php endforeach ?>
            <?php if ($this->redirect): ?>
                <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
            <?php endif ?>
        <?php echo $this->form()->closeTag() ?>
        <p>
            Already registered? <a href="<?php echo $this->url('zfcuser/login') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">Log In</a>
        </p>
        </div>
    </div>
    <div class="span8 text-center padTop20">
        <img src="<?php echo $this->basePath() ?>/images/sac-logo.png" alt="">
    </div>
</div>
