<?php
$title = 'Add new process';
$this->headTitle($title.' - ');
?>

<script>
        tinyMCE.init({
            mode : "textareas",
            theme : "advanced",
                        //elements : "textareaId",
            plugins : "advimage,advlink,media,contextmenu,table",
            theme_advanced_buttons1_add_before : "newdocument,separator",
            theme_advanced_buttons1_add : "fontselect,fontsizeselect",
            theme_advanced_buttons2_add : "separator,forecolor,backcolor,liststyle",
            theme_advanced_buttons2_add_before: "cut,copy,separator,",
            theme_advanced_buttons3_add_before : "",
            theme_advanced_buttons3_add : "media,tablecontrols",
            theme_advanced_toolbar_location : "top",
            theme_advanced_toolbar_align : "left",
            extended_valid_elements : "hr[class|width|size|noshade]",
            paste_use_dialog : false,
            theme_advanced_resizing : true,
            theme_advanced_resize_horizontal : true,
            apply_source_formatting : true,
            force_br_newlines : true,
            force_p_newlines : false,  
            relative_urls : true
        });
</script>
<div id="processWrapper">
	<h1><?php echo $this->escapeHtml($title); ?></h1>
	<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('process', array('action' => 'add')));
	$form->prepare();
	
	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('processId'));
	
	?>
	<div class="clearBoth"></div>
	<?php 
		//$form->get('teams')->setLabel('Choose Team');
		echo $this->formRow($form->get('status'));
	?>
	<div class="clearBoth"><br/></div>	
	<div class="leftSide pull-left">
		<div class="pull-left">
			<?php $objName = $form->get('name'); ?>
			<div class="pull-right">
				<?php echo $this->formInput($objName); ?>
			</div>
			<div class="pull-right processLabel"><?php echo $objName->getLabel(); ?></div>
		</div>
		<div class="clearBoth"></div>
		<div class="pull-left">
			<?php $objClientName = $form->get('clientName'); ?>
			<div class="pull-right">
				<?php echo $this->formInput($objClientName); ?>
			</div>
			<div class="pull-right processLabel"><?php echo $objClientName->getLabel(); ?></div>
		</div>
		<div class="clearBoth"></div>
		<div class="pull-left">
			<?php $objOwner = $form->get('owner'); ?>
			<div class="pull-right">
				<?php echo $this->formInput($objOwner); ?>
			</div>
			<div class="pull-right processLabel"><?php echo $objOwner->getLabel(); ?></div>
		</div>
	</div>
	<div class="rightSide pull-right">
		<div class="pull-left">
			<?php $objContactPerson = $form->get('contactPerson'); ?>
			<div class="pull-right">
				<?php echo $this->formInput($objContactPerson); ?>
			</div>
			<div class="pull-right processLabel"><?php echo $objContactPerson->getLabel(); ?></div>
		</div>
		<div class="clearBoth"></div>
		<div class="pull-left">
			<?php $objContactEmail = $form->get('contactEmail'); ?>
			<div class="pull-right">
				<?php echo $this->formInput($objContactEmail); ?>
			</div>
			<div class="pull-right processLabel"><?php echo $objContactEmail->getLabel(); ?></div>
		</div>
		<div class="clearBoth"></div>
		<div class="pull-left">
			<?php $objContactNumber = $form->get('contactNumber'); ?>
			<div class="pull-right">
				<?php echo $this->formInput($objContactNumber); ?>
			</div>
			<div class="pull-right processLabel"><?php echo $objContactNumber->getLabel(); ?></div>
		</div>
	</div>
	<div class="clearBoth"></div>
	<div class="pull-left processTextareaContainer">
		<?php $objMarginRate = $form->get('marginRate'); ?>
		<div class="pull-right">
			<?php echo $this->formInput($objMarginRate); ?>
		</div>
		<div class="pull-right processLabel"><?php echo $objMarginRate->getLabel(); ?></div>
	</div>
	
	<div class="clearBoth"></div>
	<?php 
		$form->get('teams')->setLabel('Choose Team');
		echo $this->formRow($form->get('teams'));
	?>
	<div class="clearBoth"><br/></div>
	<div>
		<?php echo $this->formRow($form->get('deliverables')); ?>
	</div>
	<div class="clearBoth"><br/></div>
	<div class="processTextareaContainer">
	<?php 
		echo $this->formRow($form->get('overview'));
		echo $this->formRow($form->get('scope'));
		echo $this->formRow($form->get('outOfScope'));
		echo $this->formRow($form->get('metrics'));
		echo $this->formRow($form->get('itResources'));
	?>
	</div>
	<div class="clearBoth"><br/></div>
	<!--<div>
		<div class="processLabels">VI. Process Flow, Manpower &amp; Cost</div>
		<div>
			<table id="processSteps">
				<thead>
					<tr>
						<th>Steps</th><th>Manpower<br/> Resource</th><th>Estimated<br/> Turnaround Time</th><th>Cost/Hour</th><th>Cost/Step</th><th>&nbsp;</th>
					</tr>
				</thead>
				<tbody>

				</tbody>
			</table>
		</div>
		<div class="processAddStep">
			<div class="pull-left">
				<div class="pull-left processAddStepLeft">Step : </div>
				<div class="pull-left"><input type="text" id="processStepName"/></div>
			</div>
			<div class="clearBoth"></div>
			<div class="pull-left">
				<div class="pull-left processAddStepLeft">Manpower Resource : </div>
				<div class="pull-left">
					<select id="processManpowerResource">
						<?php foreach($resources as $resource): ?>
						<option value="<?php echo $resource->resourceId; ?>"><?php echo $resource->description; ?></option>
						<?php endforeach; ?>
					</select>
				</div>
			</div>
			<div class="clearBoth"></div>
			<div class="pull-left">
				<div class="pull-left processAddStepLeft">Estimated Turnaround Time : </div>
				<div class="pull-left"><input type="text" id="processTurnaroundTime"/></div>
				<div class="pull-left marLeft10"><button id="processAddStepButton" type="button">Add Step</button></div>
			</div>
			<table id="processStepRow" class="hide">
				<tr class="processStepRows">
					<td class="processStepsRow1"></td>
					<td class="processStepsRow2"></td>
					<td class="processStepsRow3"></td>
					<td class="processStepsRow4"></td>
					<td class="processStepsRow5"></td>
					<td class="processStepsRow6">
						<a href="javascript://" class="processEditStep">Edit</a>
						<a href="javascript://" class="processSaveStep hide">Save</a>
						<br/><a href="javascript://" class="processRemoveStep">Remove</a>
						<input type="hidden" name="step1[][steps]" class="processStepNameValue" />
						<input type="hidden" name="step1[][resourceId]" class="processManpowerResourceValue" />
						<input type="hidden" name="step1[][turnaroundTime]" class="processTurnaroundTimeValue" />
						<input type="hidden" name="step1[][costPerHour]" class="processCostHourValue" />
						<input type="hidden" name="step1[][costPerStep]"  class="processCostStepValue" />
					</td>
				</tr>
			</table>

		</div>
	</div>
	<div class="clearBoth"><br/></div>//-->
    <div>
    	<span class="processLabels">VI. Samples </span><br/>
        <input type="file" maxlength="1" class="multi max-1 accept-gif|jpg|png" name="sampleFiles" value="">
    </div>
</div>

<div class="form-actions text-right">
	<a href="<?php echo $this->url('dashboard') ?>" class="btn pull-left"> <i
		class="icon-chevron-left"></i> Back to Dashboard
	</a>

	<?php echo $this->formSubmit($form->get('submit')) ?>
	<a href="<?php echo $this->url('process') ?>" class="btn btn-danger">Cancel</a>
</div>
<?php echo $this->form()->closeTag(); ?>