<?php
$title = 'Delete process';
$this->headTitle($title.' - ');
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($process->name); ?>' for
    '<?php echo $this->escapeHtml($process->clientName); ?>'?
</p>
<?php
$url = $this->url('process', array(
    'action' => 'delete',
    'id'     => $this->processId,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="processId" value="<?php echo (int) $process->processId; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>