<?php
$title = 'Version List';
$this->headTitle($title.' - ');
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<br/>

<table class="table">
<tr>
	<th>Process ID</th>
    <th>Name</th>
    <th>Client Name</th>
    <th>Contact Person</th>
    <th>&nbsp;</th>
</tr>
<tr>
	<td><?php echo $this->escapeHtml($parent->processId);?></td>
    <td><?php echo $this->escapeHtml($parent->name);?></td>
    <td><?php echo $this->escapeHtml($parent->clientName);?></td>
    <td><?php echo $this->escapeHtml($parent->contactPerson);?></td>
    <td>
        <a href="<?php echo $this->url('process',
            array('action'=>'edit', 'id' => $parent->processId));?>">Edit</a>
        <a href="<?php echo $this->url('process',
            array('action'=>'delete', 'id' => $parent->processId));?>">Delete</a>
    </td>
</tr>
<?php foreach ($processes as $process) : ?>
<tr>
	<td><?php echo $this->escapeHtml($process->processId);?></td>
    <td><?php echo $this->escapeHtml($process->name);?></td>
    <td><?php echo $this->escapeHtml($process->clientName);?></td>
    <td><?php echo $this->escapeHtml($process->contactPerson);?></td>
    <td>
        <a href="<?php echo $this->url('process',
            array('action'=>'edit', 'id' => $process->processId));?>">Edit</a>
        <a href="<?php echo $this->url('process',
            array('action'=>'delete', 'id' => $process->processId));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>