<?php
$title = 'Add new resource';
$this->headTitle($title.' - ');
?>
<h1>
	<i class="icon-large icon-briefcase"></i>
	<?php echo $this->escapeHtml($title); ?>
</h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('resource', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="row-fluid text-center">
	<div class="span12 offset1 text-center">
		<?php 
		echo $this->formHidden($form->get('resourceId'));

		echo $this->formRow($form->get('teamId'));
		echo $this->formRow($form->get('salaryGradeId'));
		echo $this->formRow($form->get('description'));
		?>
	</div>
</div>

<div class="form-actions text-right">
	<a href="<?php echo $this->url('dashboard') ?>" class="btn pull-left">
		<i class="icon-chevron-left"></i> Back to Dashboard
	</a>

	<?php echo $this->formSubmit($form->get('submit')) ?>
	<a href="<?php echo $this->url('resource') ?>" class="btn btn-danger">Cancel</a>
</div>
<?php echo $this->form()->closeTag(); ?>