<div class="page-header">
    <h1 class="text-center"><span class="sa-green">StraightArrow's</span> <span class="sa-orange">Process Management System</span></h1>
</div>
<div class="row-fluid">
    <br/>
    <div class="row-fluid">
        <p class="span4">
            <a class="btn btn-large btn-block" href="<?php echo $this->url('finance') ?>">
                <i class="icon-large icon-money"></i> Finance Settings
            </a>
        </p>
        <p class="span4">
            <a class="btn btn-large btn-block" href="<?php echo $this->url('salary') ?>">
                <i class="icon-large icon-tasks"></i> Salaries
            </a>
        </p>
        <p class="span4">
            <a class="btn btn-large btn-block" href="<?php echo $this->url('team') ?>">
                <i class="icon-large icon-group"></i> Teams
            </a>
        </p>
    </div>
    <div class="row-fluid">
        <p class="span4">
            <a class="btn btn-large btn-block" href="<?php echo $this->url('user') ?>">
                <i class="icon-large icon-user"></i> Users
            </a>
        </p>
        <p class="span4">
            <a class="btn btn-large btn-block" href="<?php echo $this->url('resource') ?>">
                <i class="icon-large icon-briefcase"></i> Resources
            </a>
        </p>
        <p class="span4">
            <a class="btn btn-large btn-block" href="<?php echo $this->url('process') ?>">
                <i class="icon-large icon-bar-chart"></i> Processes
            </a>
        </p>
    </div>
</div>
